// src/services/ai_quant_lab/AIQuantLabTypes.h
#pragma once
#include <QColor>
#include <QCoreApplication>
#include <QJsonObject>
#include <QString>
#include <QVector>

namespace fincept::services::quant {

struct QuantModule {
    QString id;
    QString label;
    QString short_label;
    QString category;
    QString category_key;
    QColor color;
    QString script;
    QString description;
};

inline QVector<QuantModule> all_quant_modules() {
    return {
        {"factor_discovery",
         QCoreApplication::translate("QuantModule", "Factor Discovery"),
         QCoreApplication::translate("QuantModule", "FACTOR"),
         QCoreApplication::translate("QuantCategory", "CORE"),
         "CORE", QColor("#FF6B35"), "ai_quant_lab/qlib_service.py",
         QCoreApplication::translate("QuantModule", "Discover alpha factors using Qlib framework")},
        {"model_library",
         QCoreApplication::translate("QuantModule", "Model Library"),
         QCoreApplication::translate("QuantModule", "MODEL"),
         QCoreApplication::translate("QuantCategory", "CORE"),
         "CORE", QColor("#00E5FF"), "ai_quant_lab/qlib_service.py",
         QCoreApplication::translate("QuantModule", "30+ ML models: LightGBM, XGBoost, LSTM, Transformer")},
        {"backtesting",
         QCoreApplication::translate("QuantModule", "Backtesting"),
         QCoreApplication::translate("QuantModule", "BTEST"),
         QCoreApplication::translate("QuantCategory", "CORE"),
         "CORE", QColor("#00D66F"), "ai_quant_lab/qlib_advanced_backtest.py",
         QCoreApplication::translate("QuantModule", "Multi-strategy backtesting with portfolio optimization")},
        {"live_signals",
         QCoreApplication::translate("QuantModule", "Live Signals"),
         QCoreApplication::translate("QuantModule", "SIGNAL"),
         QCoreApplication::translate("QuantCategory", "CORE"),
         "CORE", QColor("#FFC400"), "ai_quant_lab/qlib_service.py",
         QCoreApplication::translate("QuantModule", "Real-time trading signal generation")},

        {"deep_agent",
         QCoreApplication::translate("QuantModule", "Deep Agent"),
         QCoreApplication::translate("QuantModule", "DAGENT"),
         QCoreApplication::translate("QuantCategory", "AI/ML"),
         "AI_ML", QColor("#9D4EDD"), "agents/rdagents/cli.py",
         QCoreApplication::translate("QuantModule", "Autonomous AI research agent (RD-Agent)")},
        {"rl_trading",
         QCoreApplication::translate("QuantModule", "RL Trading"),
         QCoreApplication::translate("QuantModule", "RL"),
         QCoreApplication::translate("QuantCategory", "AI/ML"),
         "AI_ML", QColor("#FF3B8E"), "ai_quant_lab/qlib_rl.py",
         QCoreApplication::translate("QuantModule", "Reinforcement learning: PPO, DQN, A2C, SAC, TD3")},
        {"online_learning",
         QCoreApplication::translate("QuantModule", "Online Learning"),
         QCoreApplication::translate("QuantModule", "ONLINE"),
         QCoreApplication::translate("QuantCategory", "AI/ML"),
         "AI_ML", QColor("#00BCD4"), "ai_quant_lab/qlib_online_learning.py",
         QCoreApplication::translate("QuantModule", "Incremental learning with concept drift detection")},
        {"meta_learning",
         QCoreApplication::translate("QuantModule", "Meta Learning"),
         QCoreApplication::translate("QuantModule", "META"),
         QCoreApplication::translate("QuantCategory", "AI/ML"),
         "AI_ML", QColor("#E040FB"), "ai_quant_lab/qlib_meta_learning.py",
         QCoreApplication::translate("QuantModule", "Few-shot learning, model selection, AutoML")},
        {"pattern_intelligence",
         QCoreApplication::translate("QuantModule", "Pattern Intelligence"),
         QCoreApplication::translate("QuantModule", "PATTERN"),
         QCoreApplication::translate("QuantCategory", "AI/ML"),
         "AI_ML", QColor("#FF9100"), "Analytics/technical_indicators.py",
         QCoreApplication::translate("QuantModule", "Technical pattern recognition and scoring")},

        {"hft",
         QCoreApplication::translate("QuantModule", "High Frequency Trading"),
         QCoreApplication::translate("QuantModule", "HFT"),
         QCoreApplication::translate("QuantCategory", "ADVANCED"),
         "ADVANCED", QColor("#F44336"), "ai_quant_lab/qlib_high_frequency.py",
         QCoreApplication::translate("QuantModule", "Order book dynamics, market making, latency optimization")},
        {"rolling_retraining",
         QCoreApplication::translate("QuantModule", "Rolling Retraining"),
         QCoreApplication::translate("QuantModule", "ROLL"),
         QCoreApplication::translate("QuantCategory", "ADVANCED"),
         "ADVANCED", QColor("#8BC34A"), "ai_quant_lab/qlib_rolling_retraining.py",
         QCoreApplication::translate("QuantModule", "Automated model retraining with rolling windows")},
        {"advanced_models",
         QCoreApplication::translate("QuantModule", "Advanced Models"),
         QCoreApplication::translate("QuantModule", "ADV"),
         QCoreApplication::translate("QuantCategory", "ADVANCED"),
         "ADVANCED", QColor("#03A9F4"), "ai_quant_lab/qlib_advanced_models.py",
         QCoreApplication::translate("QuantModule", "LSTM, GRU, Transformer, Localformer, HIST, GAT")},
        {"feature_engineering",
         QCoreApplication::translate("QuantModule", "Feature Engineering"),
         QCoreApplication::translate("QuantModule", "FEAT"),
         QCoreApplication::translate("QuantCategory", "ADVANCED"),
         "ADVANCED", QColor("#26C6DA"), "ai_quant_lab/qlib_feature_engineering.py",
         QCoreApplication::translate("QuantModule", "Technical indicators, factor selection, expression engine")},
        {"portfolio_opt",
         QCoreApplication::translate("QuantModule", "Portfolio Optimization"),
         QCoreApplication::translate("QuantModule", "PORTOPT"),
         QCoreApplication::translate("QuantCategory", "ADVANCED"),
         "ADVANCED", QColor("#66BB6A"), "ai_quant_lab/qlib_portfolio_opt.py",
         QCoreApplication::translate("QuantModule", "Black-Litterman, HRP, Min-Variance, Max-Sharpe, EF")},
        {"factor_evaluation",
         QCoreApplication::translate("QuantModule", "Factor Evaluation"),
         QCoreApplication::translate("QuantModule", "EVAL"),
         QCoreApplication::translate("QuantCategory", "ADVANCED"),
         "ADVANCED", QColor("#FFA726"), "ai_quant_lab/qlib_evaluation.py",
         QCoreApplication::translate("QuantModule", "IC metrics, factor returns, risk metrics, factor scoring")},
        {"strategy_builder",
         QCoreApplication::translate("QuantModule", "Strategy Builder"),
         QCoreApplication::translate("QuantModule", "STRAT"),
         QCoreApplication::translate("QuantCategory", "ADVANCED"),
         "ADVANCED", QColor("#AB47BC"), "ai_quant_lab/qlib_strategy.py",
         QCoreApplication::translate("QuantModule", "TopK-Dropout, Enhanced Indexing, Risk Parity, Mean-Variance")},
        {"data_processors",
         QCoreApplication::translate("QuantModule", "Data Processors"),
         QCoreApplication::translate("QuantModule", "PROC"),
         QCoreApplication::translate("QuantCategory", "ADVANCED"),
         "ADVANCED", QColor("#EF5350"), "ai_quant_lab/qlib_data_processors.py",
         QCoreApplication::translate("QuantModule", "10 normalizers: zscore, winsorize, cs_rank, tanh, fillna")},
        {"quant_reporting",
         QCoreApplication::translate("QuantModule", "Quant Reporting"),
         QCoreApplication::translate("QuantModule", "REPORT"),
         QCoreApplication::translate("QuantCategory", "ANALYTICS"),
         "ANALYTICS", QColor("#78909C"), "ai_quant_lab/qlib_reporting.py",
         QCoreApplication::translate("QuantModule", "IC reports, cumulative returns, risk analysis, model performance")},

        {"cfa_quant",
         QCoreApplication::translate("QuantModule", "CFA Quant"),
         QCoreApplication::translate("QuantModule", "CFA"),
         QCoreApplication::translate("QuantCategory", "ANALYTICS"),
         "ANALYTICS", QColor("#FF6B35"), "Analytics/quant_analytics_cli.py",
         QCoreApplication::translate("QuantModule", "Trend, ARIMA, ML prediction, PCA, bootstrap")},
        {"gs_quant",
         QCoreApplication::translate("QuantModule", "GS Quant"),
         QCoreApplication::translate("QuantModule", "GS"),
         QCoreApplication::translate("QuantCategory", "ANALYTICS"),
         "ANALYTICS", QColor("#9D4EDD"), "Analytics/gs_quant_wrapper/gs_quant_service.py",
         QCoreApplication::translate("QuantModule", "Risk metrics, portfolio analytics, options Greeks, VaR")},
        {"statsmodels",
         QCoreApplication::translate("QuantModule", "Statsmodels"),
         QCoreApplication::translate("QuantModule", "STATS"),
         QCoreApplication::translate("QuantCategory", "ANALYTICS"),
         "ANALYTICS", QColor("#2196F3"), "Analytics/statsmodels_wrapper/statsmodels_service.py",
         QCoreApplication::translate("QuantModule", "OLS, ARIMA, stationarity, ACF/PACF, Granger causality, descriptive")},
        {"functime",
         QCoreApplication::translate("QuantModule", "Functime"),
         QCoreApplication::translate("QuantModule", "FUNC"),
         QCoreApplication::translate("QuantCategory", "ANALYTICS"),
         "ANALYTICS", QColor("#4CAF50"), "Analytics/functime_wrapper/functime_service.py",
         QCoreApplication::translate("QuantModule", "Forecasting, anomaly detection, seasonality, intervals, stationarity")},
        {"fortitudo",
         QCoreApplication::translate("QuantModule", "Fortitudo"),
         QCoreApplication::translate("QuantModule", "FORT"),
         QCoreApplication::translate("QuantCategory", "ANALYTICS"),
         "ANALYTICS", QColor("#FF5722"), "Analytics/fortitudo_tech_wrapper/fortitudo_service.py",
         QCoreApplication::translate("QuantModule", "Portfolio metrics, MV/CVaR optimization, efficient frontier, exp-decay weights")},
        {"gluonts",
         QCoreApplication::translate("QuantModule", "GluonTS"),
         QCoreApplication::translate("QuantModule", "GLUON"),
         QCoreApplication::translate("QuantCategory", "ANALYTICS"),
         "ANALYTICS", QColor("#795548"), "Analytics/gluonts_wrapper/gluonts_service.py",
         QCoreApplication::translate("QuantModule", "Probabilistic + quantile forecasts, distribution fits, forecast evaluation, baselines")},
    };
}

inline QStringList quant_categories() {
    return {"CORE", "AI_ML", "ADVANCED", "ANALYTICS"};
}

} // namespace fincept::services::quant
